# Generated by Django 4.2.2 on 2023-06-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_firs_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mail',
            new_name='email',
        ),
    ]
