# Generated by Django 4.2.2 on 2023-06-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_hstory', 'Can view history')]},
        ),
    ]
